Segmentation branch
Digiratory/Pollen-Analyzer pull request #8
Opened 2024-07-13 16:17 UTC by Miryz21

Pull request for verifying the work on the segmentation model.

2024-07-14 09:19 UTC, Sinitca-Aleksandr requested changes

2024-07-14 09:19 UTC, Sinitca-Aleksandr commented on .gitignore
.gitignore удалять не надо.

2024-07-14 09:19 UTC, Sinitca-Aleksandr commented on instance_segmentation/coco_eval.py
Это же позаимствовано откуда-то? 
Добавь хедер к файлу или в docstring позаимствованных функций информацию об авторе и лицензии

2024-07-14 09:19 UTC, Sinitca-Aleksandr commented on instance_segmentation/coco_utils.py
Это же позаимствовано откуда-то? 
Добавь хедер к файлу или в docstring позаимствованных функций информацию об авторе и лицензии

2024-07-14 09:19 UTC, Sinitca-Aleksandr commented on instance_segmentation/engine.py
> +        lr_scheduler = torch.optim.lr_scheduler.LinearLR(
`lr_scheduler`  будет жить только в нулевой эпохе.
 Эту функцию либо в класс заворачивать надо, либо делать переменную статической (лучше в класс -- это более очевидный способ состояние хранить)

Либо как вариант, передавать его как аргумент и управлять полностью снаружи

2024-07-14 09:19 UTC, Sinitca-Aleksandr commented on instance_segmentation/train_model.py
> +    # load a coco-model
это ж не коко

2024-07-14 09:19 UTC, Sinitca-Aleksandr commented on instance_segmentation/train_model.py
> +    dataset, dataset_test = divide_dataset(0.7, f_d)
Оно не будет корректно с методической точки зрения работать.

У тебя датасет синтетический, со случайным набором объектов. Лучше изначально создавать для датасета из непересекающихся наборов данных. 

Для валидации можно будет оставить как есть синтетику, но разделить исходные данные для генерации (как минимум на уровне картинки. Можно попробовать на уровне вида, то есть в валидацию добавить виды которых в обучении нет). Для теста -- в августе разметим какое-то количество реальных картинок, наверное.

2024-09-02 17:21 UTC, Sinitca-Aleksandr requested changes

2024-09-02 17:21 UTC, Sinitca-Aleksandr commented on .gitignore
Что это за жуть? 
1. Верни старые игноры
2. Все файлы перечислять не надо, достаточно по маске

2024-09-02 17:21 UTC, Sinitca-Aleksandr commented on Instance Segmentation/coco_eval.py
Уведомление о лицензии обычно делается многострочным комментарием 
`
"""
License
"""
`

2024-09-02 17:21 UTC, Sinitca-Aleksandr commented on Instance Segmentation/image_from_mask.py
> +
Добавь в readme.md информацию как это запускать

2024-09-02 17:21 UTC, Sinitca-Aleksandr commented on Instance Segmentation/image_from_mask.py
> +        segment_objects(path_to_model, output_dir, image_path, score_threshold, mask_threshold, name)
В конце файла должна быть пустая строка

2024-09-02 17:21 UTC, Sinitca-Aleksandr commented on Instance Segmentation/test_model.py
> +    # writer.add_scalars('Validation tables', eval_res, epoch*len(data_loader_test))
Что это? Если не нужно -- удаляй. Если оставил на будущее -- вынеси в отдельный метод

2024-09-02 17:21 UTC, Sinitca-Aleksandr commented on Instance Segmentation/train_model.py
> +    dataset = AugmentImageDataset(pollen_dir, noise_dir, back_usages=10, objects_per_image=(1, 6), transform=get_transform(True),
В Readme добавь инструкцию как запускать и откуда брать данные

2024-09-02 17:21 UTC, Sinitca-Aleksandr commented on requirements.txt
> +torch==2.2.2
Поставь сверху коммент что это для сегментации

2024-09-03 14:45 UTC, Miryz21 commented on Instance Segmentation/coco_eval.py
Сделано

2024-09-03 14:45 UTC, Miryz21 commented on Instance Segmentation/image_from_mask.py
> +        segment_objects(path_to_model, output_dir, image_path, score_threshold, mask_threshold, name)
Добавил

2024-09-03 14:45 UTC, Miryz21 commented on Instance Segmentation/test_model.py
> +    # writer.add_scalars('Validation tables', eval_res, epoch*len(data_loader_test))
Убрал, если что подниму опять

2024-09-03 14:46 UTC, Miryz21 commented on requirements.txt
> +torch==2.2.2
Сделал, также добавил модуль для чтения cvat

2024-09-05 11:08 UTC, Miryz21 commented on .gitignore
исправил

2024-09-17 16:09 UTC, Miryz21 commented on Instance Segmentation/train_model.py
> +    dataset = AugmentImageDataset(pollen_dir, noise_dir, back_usages=10, objects_per_image=(1, 6), transform=get_transform(True),
добавил!

2024-09-17 16:09 UTC, Miryz21 commented on Instance Segmentation/image_from_mask.py
> +
добавил ридмик

2024-09-24 15:30 UTC, Sinitca-Aleksandr submitted a review, later dismissed

2024-09-24 17:05 UTC, Sinitca-Aleksandr approved these changes

2024-09-24 17:05 UTC, merged